[package]
name = "mkl82z7-pac"
version = "0.1.0"
authors = ["Sindre Hansen <sindrehansen92@gmail.com>"]
edition = "2018"

[dependencies]
bare-metal = "0.2.5"
vcell = "0.1.2"
cortex-m = "0.5.10"

[dependencies.cortex-m-rt]
optional = true
version = "0.6.12"

[features]
rt = ["cortex-m-rt/device"]
